### ISSUE TITLE
Copy of the arXiv paper in this repo, release of dataset for multi-agent mapping experiments?

### ISSUE THREAD

**Issue by Mechazo11** [XuRobotics/SLIDE_SLAM#2]
Hi @XuRobotics,

Thank you very much for starting this repository on your upcoming ```SlideSlam``` paper. I too am working with metric-semantic data for multi-agent mapping problems. 

I was wondering if you would kindly share a copy of the paper in this repo. Unfortunately, the url to [arXiv](SlideSLAM: Sparse, Lightweight, Decentralized Metric-Semantic SLAM for Multi-Robot Navigation) does not work. If you could kindly provide a copy of the paper in this repo, I will appreciate it. I am very much interested to see how you approached the ```lightweight``` aspect of map representation using semantic and metric data.

On a different note, will this dataset be made publicly available to use other multi-agent mapping systems for experimentation purposes?

With best,
@Mechazo11

**Comment by XuRobotics** [comment]
Thanks for your interest, and it’s great to hear that you are also interested in and working on the same research problem!

I have added a link directly to the README of this repo that points to our arXiv paper. Would that work for you? I want to avoid directly including a copy on the github because:
1. It will increase the download size of this repo to be much larger than what is required for the code itself.
2. We will be updating our arXiv paper as we introduce new functionalities to our system. You can use the same link to access the latest version. 

Regarding data, thanks for bringing this up. We will discuss this with the rest of our team and try to release some of the data.

**Comment by Mechazo11** [comment]
Hi @XuRobotics 

Thank you for your prompt response. Yes, the arXiv link works now, thank you very much. I agree with your logic, adding the whole paper would increase the size of the workspace.

I will keep an eye out for the dataset. It would be very helpful for my project since getting a multiagent dataset with ground truth data is very hard to comeby in academia.

Good luck with your paper

With best,
@Mechazo11
